- name: Настройка NTP сервера
  become: true
  block:
    - name: Удаляем все записи с адресами NTP серверов
      ansible.builtin.lineinfile:
        path: /etc/chrony/chrony.conf
        regexp: '^\s*(server|pool)\s'
        state: absent

    - name: Добавляем записи с нужными адресами
      ansible.builtin.lineinfile:
        path: /etc/chrony/chrony.conf
        line: "{{ item }}"
        state: present
        create: true
        insertafter: EOF
        mode: "0740"
      loop: "{{ ntp_servers }}"

    - name: Разрешаем IP адреса клиентов
      ansible.builtin.lineinfile:
        path: /etc/chrony/chrony.conf
        line: "allow {{ item }}"
        state: present
        create: true
        insertafter: EOF
        mode: "0740"
      loop: "{{ client_networks }}"

    - name: Устанавливаем запуск сервиса при включении
      ansible.builtin.service:
        name: chrony
        enabled: true
        state: restarted
