- name: Настройка NTP сервера
  block:
    - name: Удаляем все записи с адресами NTP серверов
      ansible.builtin.lineinfile:
        path: /etc/chrony/chrony.conf
        regexp: '^\s*(server|pool)\s'
        state: absent

    - name: Добавляем записи с нужными адресами
      ansible.builtin.lineinfile:
        path: /etc/chrony/chrony.conf
        line: "{{ item }}"
        state: present
        create: yes
        insertafter: EOF
      loop: "{{ ntp_servers }}"

    - name: Разрешаем IP адреса клиентов
      ansible.builtin.lineinfile:
        path: /etc/chrony/chrony.conf
        line: "allow {{ item }}"
        state: present
        create: yes
        insertafter: EOF
      loop: "{{ client_networks }}"
 
    - name: Устанавливаем запуск сервиса при включении
      ansible.builtin.service:
        name: chrony
        enabled: yes
        state: restarted

  become: yes