- name: Настройка NTP сервера
  become: true
  block:
    - name: Удаляем все записи с адресами NTP серверов
      ansible.builtin.lineinfile:
        path: /etc/chrony/chrony.conf
        regexp: '^\s*(server|pool)\s'
        state: absent

    - name: Добавляем записи с нужными адресами
      ansible.builtin.lineinfile:
        path: /etc/chrony/chrony.conf
        line: "{{ item }}"
        state: present
        create: true
        insertafter: EOF
        mode: "0740"
      loop: "{{ ntp_servers }}"

    - name: Разрешаем IP адреса клиентов
      ansible.builtin.lineinfile:
        path: /etc/chrony/chrony.conf
        line: "allow {{ item }}"
        state: present
        create: true
        insertafter: EOF
        mode: "0740"
      loop: "{{ client_networks }}"

    - name: Устанавливаем запуск сервиса при включении
      ansible.builtin.service:
        name: chrony
        enabled: true
        state: restarted

    - name: Сохранение факта о ip адресе сервера
      ansible.builtin.set_fact:
        service_ip: "{{ ansible_facts['eth0']['ipv4']['address'] }}"
        cacheable: true

- name: Создание локального DNS сервера
  become: true
  block:
    - name: Установка необходимых пакетов
      ansible.builtin.apt:
        name:
          - dnsmasq
        state: present
        update_cache: true

    - name: Конфигурация DNS сервера
      ansible.builtin.copy:
        dest: /etc/dnsmasq.conf
        content: |
          interface=eth0

          port=53

          address=/prod.registry.local/{{ hostvars['prod-node-1']['ansible_facts']['runner_ip'] }}
          address=/dev.registry.local/{{ hostvars['dev-node-1']['ansible_facts']['runner_ip'] }}

          server=8.8.8.8
          server=1.1.1.1
        mode: "0744"

    - name: Перезапуск DNS серавера с новыми конфигурациями
      ansible.builtin.service:
        name: dnsmasq
        state: restarted
        enabled: true
