---
- name: Выбор имени раннера по label
  ansible.builtin.set_fact:
    runner_host: >
      {% if label == 'prod' %}
        prod-node-1
      {% elif label == 'dev' %}
        dev-node-1
      {% endif %}

- name: Добавление ноды в swarm кластер
  community.docker.docker_swarm:
    state: join
    join_token: "{{ hostvars[runner_host | trim]['ansible_facts']['token_manager'] }}"
    remote_addrs: "{{ hostvars[runner_host | trim]['ansible_facts']['runner_ip'] }}"

- name: Проверка наличия файла daemon.json
  ansible.builtin.file:
    path: /etc/docker/daemon.json
    state: touch
    mode: "0744"
  become: true

- name: Разрешение использовать HTTP для ip адреса runner хоста
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    mode: "0744"
    content: |
      {
        "insecure-registries": ["{{ hostvars[runner_host | trim]['ansible_facts']['runner_ip'] }}:5000"]
      }
  become: true

- name: Перезапуск сервиса Docker
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: true
  become: true
