---
- name: Конфигурация серверов
  hosts: servers
  roles:
    - role: preconfig
      tags: preconfig

    - role: users-init
      tags: users-init

    - role: service-creator
      tags: service-creator

    - role: service-connector
      tags: service-connector

    - role: actions-runner
      tags: actions-runner