- name: Добавление NTP сервера
  become: true
  block:
    - name: Удаляем все записи с адресами NTP серверов
      ansible.builtin.lineinfile:
        path: /etc/chrony/chrony.conf
        regexp: '^\s*(server|pool)\s'
        state: absent

    - name: Добавляем записи с нужными адресами
      ansible.builtin.lineinfile:
        path: /etc/chrony/chrony.conf
        line: "server {{ service_ip }} iburst"
        state: present
        create: true
        insertafter: EOF
        mode: "0740"

    - name: Устанавливаем запуск сервиса при включении
      ansible.builtin.service:
        name: chrony
        enabled: true
        state: restarted

- name: Добавление NTP сервера
  become: true
  block:
    - name: Удаляем все записи с адресами NTP серверов
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        content: nameserver {{ service_ip }}
        mode: "0744"
